<?php

declare(strict_types=1);

return [
    'name' => env('ADMIN_NAME', config('commerce.name', 'Commerce Framework')),

    'sidebar' => [
        'width' => '16rem',
        'collapsed_width' => '4.5rem',
        'default_collapsed' => false,
        'storage_key' => 'commerce.admin.sidebar.collapsed',
        'groups_storage_key' => 'commerce.admin.sidebar.groups',
    ],

    'theme' => [
        'default' => 'system',
        'storage_key' => 'commerce.admin.theme',
    ],

    'locale' => [
        'default' => 'th',
        'available' => [
            'th' => 'ไทย',
            'en' => 'English',
        ],
        'session_key' => 'commerce.locale',
        'storage_key' => 'commerce.admin.locale',
    ],

    'command_palette' => [
        'enabled' => true,
        'shortcut' => 'mod+k',
    ],

    'navigation' => [
        [
            'type' => 'link',
            'id' => 'home',
            'label' => 'Home',
            'icon' => 'home',
            'route' => 'admin.dashboard',
            'permission' => 'reports.dashboard.view',
            'order' => 10,
            'aliases' => ['Dashboard'],
        ],
        [
            'type' => 'group',
            'id' => 'orders',
            'label' => 'Orders',
            'icon' => 'shopping-cart',
            'order' => 20,
            'default_open' => false,
            'children' => [
                ['type' => 'link', 'label' => 'Orders', 'route' => 'admin.orders.index', 'permission' => 'orders.order.view'],
                ['type' => 'link', 'label' => 'Payments', 'route' => 'admin.payments.index', 'permission' => 'payment.payment.view'],
            ],
        ],
        [
            'type' => 'group',
            'id' => 'products',
            'label' => 'Products',
            'icon' => 'cube',
            'order' => 30,
            'default_open' => false,
            'children' => [
                ['type' => 'link', 'label' => 'Products', 'route' => 'admin.products.index', 'permission' => 'product.product.view', 'aliases' => ['Catalog']],
                ['type' => 'link', 'label' => 'Collections', 'route' => 'admin.catalog.index', 'permission' => 'catalog.category.view', 'aliases' => ['Categories']],
                ['type' => 'link', 'label' => 'Inventory', 'route' => 'admin.inventory.index', 'permission' => 'inventory.stock.view'],
            ],
        ],
        [
            'type' => 'group',
            'id' => 'customers',
            'label' => 'Customers',
            'icon' => 'users',
            'order' => 40,
            'default_open' => false,
            'children' => [
                ['type' => 'link', 'label' => 'Customers', 'route' => 'admin.customers.index', 'permission' => 'customers.customer.view'],
                ['type' => 'link', 'label' => 'Leads', 'route' => 'admin.crm.leads.index', 'permission' => 'crm.lead.view', 'aliases' => ['CRM']],
            ],
        ],
        [
            'type' => 'group',
            'id' => 'online-store',
            'label' => 'Online Store',
            'icon' => 'photo',
            'order' => 50,
            'default_open' => false,
            'children' => [
                ['type' => 'link', 'label' => 'Home', 'route' => 'admin.cms.homepage.edit', 'permission' => 'cms.page.view', 'module' => 'cms'],
                ['type' => 'link', 'label' => 'Pages', 'route' => 'admin.cms.pages.index', 'permission' => 'cms.page.view', 'module' => 'cms'],
                ['type' => 'link', 'label' => 'Blog', 'route' => 'admin.cms.posts.index', 'permission' => 'cms.post.view', 'module' => 'blog'],
                ['type' => 'link', 'label' => 'Navigation', 'route' => 'admin.navigation.show', 'permission' => 'navigation.menu.view', 'module' => 'navigation'],
                ['type' => 'link', 'label' => 'Theme', 'route' => 'admin.settings.appearance.show', 'permission' => 'settings.setting.view', 'module' => 'settings', 'aliases' => ['Storefront']],
                ['type' => 'link', 'label' => 'Files', 'route' => 'admin.media.index', 'permission' => 'media.media.view', 'module' => 'media'],
                ['type' => 'link', 'label' => 'Header menu', 'route' => 'admin.storefront.navigation.show', 'permission' => 'settings.setting.view'],
                ['type' => 'link', 'label' => 'Footer', 'route' => 'admin.settings.footer.show', 'permission' => 'settings.setting.view', 'module' => 'footer-management'],
                ['type' => 'link', 'label' => 'Blog categories', 'route' => 'admin.cms.categories.index', 'permission' => 'cms.category.view', 'module' => 'blog'],
                ['type' => 'link', 'label' => 'Tags', 'route' => 'admin.cms.tags.index', 'permission' => 'cms.tag.view', 'module' => 'blog'],
                ['type' => 'link', 'label' => 'Hero banners', 'route' => 'admin.cms.hero-banners.index', 'permission' => 'cms.page.view', 'module' => 'cms'],
                ['type' => 'link', 'label' => 'Promo banners', 'route' => 'admin.cms.promotion-banners.index', 'permission' => 'cms.page.view', 'module' => 'cms'],
                ['type' => 'link', 'label' => 'FAQ', 'route' => 'admin.cms.faq-entries.index', 'permission' => 'cms.page.view', 'module' => 'cms'],
            ],
        ],
        [
            'type' => 'group',
            'id' => 'marketing',
            'label' => 'Marketing',
            'icon' => 'tag',
            'order' => 60,
            'default_open' => false,
            'children' => [
                ['type' => 'link', 'label' => 'Discounts', 'route' => 'admin.promotions.index', 'permission' => 'promotion.promotion.view', 'aliases' => ['Promotions']],
            ],
        ],
        [
            'type' => 'group',
            'id' => 'analytics',
            'label' => 'Analytics',
            'icon' => 'chart-bar',
            'order' => 70,
            'default_open' => false,
            'children' => [
                ['type' => 'link', 'label' => 'Overview', 'route' => 'admin.reports.index', 'permission' => 'reports.dashboard.view'],
                ['type' => 'link', 'label' => 'Sales Reports', 'route' => 'admin.reports.sales.index', 'permission' => 'reports.dashboard.view'],
                ['type' => 'link', 'label' => 'Order Reports', 'route' => 'admin.reports.orders.index', 'permission' => 'reports.dashboard.view'],
                ['type' => 'link', 'label' => 'Product Reports', 'route' => 'admin.reports.products.index', 'permission' => 'reports.dashboard.view'],
            ],
        ],
        [
            'type' => 'group',
            'id' => 'pos',
            'label' => 'Point of Sale',
            'icon' => 'device-tablet',
            'order' => 80,
            'default_open' => false,
            'module' => 'pos',
            'children' => [
                ['type' => 'link', 'label' => 'POS', 'route' => 'pos.index', 'permission' => 'pos.terminal.use', 'module' => 'pos'],
                ['type' => 'link', 'label' => 'Registers', 'route' => 'admin.pos.registers.index', 'permission' => 'pos.register.view', 'module' => 'pos'],
            ],
        ],
        [
            'type' => 'group',
            'id' => 'warehouse',
            'label' => 'Warehouse',
            'icon' => 'qr-code',
            'order' => 90,
            'default_open' => false,
            'children' => [
                ['type' => 'link', 'label' => 'Scanner', 'route' => 'warehouse.index', 'permission' => 'warehouse.scan', 'module' => 'warehouse'],
                ['type' => 'link', 'label' => 'Barcode Center', 'route' => 'admin.barcode.index', 'permission' => 'barcode.print', 'module' => 'barcode'],
            ],
        ],
        [
            'type' => 'group',
            'id' => 'marketplace',
            'label' => 'Marketplace',
            'icon' => 'shopping-bag',
            'order' => 100,
            'default_open' => false,
            'module' => 'marketplace',
            'children' => [
                ['type' => 'link', 'label' => 'Sellers', 'route' => 'admin.marketplace.sellers.index', 'permission' => 'marketplace.seller.view', 'module' => 'marketplace'],
                ['type' => 'link', 'label' => 'Marketplace Operations', 'route' => 'admin.marketplace.commissions.index', 'permission' => 'marketplace.commission.view', 'module' => 'marketplace'],
            ],
        ],
        [
            'type' => 'group',
            'id' => 'platform',
            'label' => 'Platform',
            'icon' => 'squares-2x2',
            'order' => 110,
            'default_open' => false,
            'children' => [
                ['type' => 'link', 'label' => 'Tenants', 'route' => 'admin.platform.tenants.index', 'permission' => 'platform.tenant.view'],
                ['type' => 'link', 'label' => 'Modules', 'route' => 'admin.system.modules.index', 'permission' => 'system.module.view'],
                ['type' => 'link', 'label' => 'Features', 'route' => 'admin.system.features.index', 'permission' => 'system.feature.view'],
            ],
        ],
        [
            'type' => 'group',
            'id' => 'settings',
            'label' => 'Settings',
            'icon' => 'cog',
            'order' => 200,
            'pinned' => true,
            'default_open' => false,
            'children' => [
                ['type' => 'link', 'label' => 'General', 'route' => 'admin.settings.website.show', 'permission' => 'settings.setting.view', 'module' => 'settings'],
                ['type' => 'link', 'label' => 'Site Identity', 'route' => 'admin.settings.site-identity.show', 'permission' => 'settings.setting.view', 'module' => 'settings'],
                ['type' => 'link', 'label' => 'Checkout & Experience', 'route' => 'admin.settings.customer-experience.show', 'permission' => 'settings.setting.view', 'module' => 'customer-experience'],
                ['type' => 'link', 'label' => 'Shipping', 'route' => 'admin.shipping.index', 'permission' => 'shipping.method.view'],
                ['type' => 'link', 'label' => 'Taxes', 'route' => 'admin.tax.index', 'permission' => 'tax.rate.view'],
                ['type' => 'link', 'label' => 'Languages', 'route' => 'admin.settings.translations.index', 'permission' => 'settings.setting.view', 'module' => 'settings'],
                ['type' => 'link', 'label' => 'Currencies', 'route' => 'admin.currencies.index', 'permission' => 'currency.currency.view'],
                ['type' => 'link', 'label' => 'Staff', 'route' => 'admin.iam.users.index', 'permission' => 'iam.user.view', 'module' => 'users'],
                ['type' => 'link', 'label' => 'Roles', 'route' => 'admin.iam.roles.index', 'permission' => 'iam.role.view', 'module' => 'roles'],
                ['type' => 'link', 'label' => 'Permissions', 'route' => 'admin.iam.permissions.index', 'permission' => 'iam.permission.view', 'module' => 'permissions'],
                ['type' => 'link', 'label' => 'Teams', 'route' => 'admin.iam.teams.index', 'permission' => 'iam.team.view'],
                ['type' => 'link', 'label' => 'Activity Logs', 'route' => 'admin.iam.audit-logs.index', 'permission' => 'iam.audit.view'],
                ['type' => 'link', 'label' => 'Security', 'route' => 'admin.iam.security.show'],
                ['type' => 'link', 'label' => 'Customer Login', 'route' => 'admin.settings.auth.show', 'permission' => 'settings.setting.view', 'module' => 'settings'],
                ['type' => 'link', 'label' => 'Email', 'route' => 'admin.settings.mail.show', 'permission' => 'settings.setting.view', 'module' => 'settings'],
                ['type' => 'link', 'label' => 'Notifications', 'route' => 'admin.notification.templates.index', 'permission' => 'notification.template.view'],
                ['type' => 'link', 'label' => 'Apps & Integrations', 'route' => 'admin.webhooks.index', 'permission' => 'webhooks.webhook.view'],
                ['type' => 'link', 'label' => 'Products', 'route' => 'admin.products.settings.show', 'permission' => 'product.product.view'],
                ['type' => 'link', 'label' => 'System', 'route' => 'admin.settings.index', 'permission' => 'settings.setting.view', 'module' => 'settings'],
            ],
        ],
    ],
];
